Beerhall/Models/Domain/Brewer.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Beerhall.Models.Domain {
    public class Brewer {
        #region Fields
        private string _name;
        private int? _turnover;
        #endregion

        #region Properties
        public int BrewerId {
            get; set;
        }

        public string Name {
            get {
                return _name;
            }
            set {
                if (string.IsNullOrWhiteSpace(value))
                    throw new ArgumentException("A brewer must have a name");
                if (value.Length > 50)
                    throw new ArgumentException("Name of brewer may not exceed 50 characters");
                _name = value;
            }
        }

        public string Description {
            get; set;
        }

        public string ContactEmail {
            get; set;
        }

        public DateTime? DateEstablished {
            get; set;
        }

        public string Street {
            get; set;
        }

        public Location Location {
            get; set;
        }

        public int? Turnover {
            get {
                return _turnover;
            }
            set {
                if (value.GetValueOrDefault() < 0)
                    throw new ArgumentException("Turnover must be positive");
                _turnover = value;
            }
        }

        public ICollection<Beer> Beers {
            get;
        }

        public int NrOfBeers => Beers.Count;

        #endregion

        #region Constructors
        public Brewer(string name) {
            Beers = new HashSet<Beer>();
            _turnover = null;
            Name = name;
        }

        public Brewer(string name, Location location, string street)
            : this(name) {
            Location = location;
            Street = street;
        }
        #endregion

        #region Methods
        public Beer AddBeer(string name, double? alcoholByVolume = null, decimal price = 0, string description = null) {
            if (name != null && Beers.Any(b => b.Name == name))
                throw new ArgumentException($"Brewer {Name} has already a beer by the name of {name}");
            Beer newBeer = new Beer(name) {
                AlcoholByVolume = alcoholByVolume,
                Description = description,
                Price = price
            };
            Beers.Add(newBeer);
            return newBeer;
        }

        public void DeleteBeer(Beer beer) {
            if (!Beers.Contains(beer))
                throw new ArgumentException($"{beer.Name} is not a {Name} beer");
            Beers.Remove(beer);
        }

        public Beer GetBy(int beerId) {
            return Beers.FirstOrDefault(b => b.BeerId == beerId);
        }

        public Beer GetBy(string name) {
            return Beers.FirstOrDefault(b => b.Name == name);
        }
        #endregion

    }
}

Beerhall/Controllers/BrewerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Beerhall.Models.Domain;
using Beerhall.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Beerhall.Controllers
{
    public class BrewerController : Controller
    {
        private readonly IBrewerRepository _brewerRepository;
        private readonly ILocationRepository _locationRepository;

        public BrewerController(IBrewerRepository brewerRepository, ILocationRepository locationRepository)
        {
            _brewerRepository = brewerRepository;
            _locationRepository = locationRepository;
        }
        public IActionResult Index()
        {
            IEnumerable<Brewer> brewers = _brewerRepository.GetAll().OrderBy(b => b.Name).ToList();
            ViewData["TotalTurnover"] = brewers.Sum(b => b.Turnover);
            return View(brewers);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Brewer brewer = _brewerRepository.GetBy(id);
            ViewData["Locations"] = new SelectList(
                _locationRepository.GetAll().OrderBy(l => l.Name),
                nameof(Location.PostalCode),
                nameof(Location.Name));
            return View(new BrewerEditViewModel(brewer));
        }

        [HttpPost]
        public IActionResult Edit(BrewerEditViewModel brewerEditViewModel, int id)
        {
            Brewer brewer = null;
            try
            {
                brewer = _brewerRepository.GetBy(id);
                MapBrewerEditViewModelToBrewer(brewerEditViewModel, brewer);
                _brewerRepository.SaveChanges();
                TempData["message"] = $"You successfully edited brewer {brewer.Name}.";
            }
            catch
            {
                TempData["error"] = $"Sorry, something went wrong, brewer {brewer?.Name} was not edited...";
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["IsEdit"] = false;
            ViewData["Locations"] = GetLocationsAsSelectList();
            return View(nameof(Edit), new BrewerEditViewModel());
        }

        [HttpPost]
        public IActionResult Create(BrewerEditViewModel brewerEditViewModel)
        {
            Brewer brewer = null;
            try
            {
                brewer = new Brewer(brewerEditViewModel.Name);
                MapBrewerEditViewModelToBrewer(brewerEditViewModel, brewer);
                _brewerRepository.Add(brewer);
                _brewerRepository.SaveChanges();
                TempData["message"] = $"You successfully created brewer {brewer.Name}.";
            }
            catch
            {
                TempData["error"] = $"Sorry, something went wrong, brewer {brewer?.Name} was not created...";
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            ViewData[nameof(Brewer.Name)] = _brewerRepository.GetBy(id).Name;
            return View();
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            Brewer brewer = null;
            try
            {
                brewer = _brewerRepository.GetBy(id);
                _brewerRepository.Delete(brewer);
                _brewerRepository.SaveChanges();
                TempData["message"] = $"You successfully deleted brewer {brewer.Name}.";
            }
            catch
            {
                TempData["error"] = $"Sorry, something went wrong, brewer {brewer?.Name} was not deleted...";
            }
            return RedirectToAction(nameof(Index));
        }

        private void MapBrewerEditViewModelToBrewer(BrewerEditViewModel brewerEditViewModel, Brewer brewer)
        {
            brewer.Name = brewerEditViewModel.Name;
            brewer.Street = brewerEditViewModel.Street;
            brewer.Location = brewerEditViewModel.PostalCode == null
                ? null
                : _locationRepository.GetBy(brewerEditViewModel.PostalCode);
            brewer.Turnover = brewerEditViewModel.Turnover;
        }

        private object GetLocationsAsSelectList()
        {
            return new SelectList(
                _locationRepository.GetAll().OrderBy(l => l.Name),
                nameof(Location.PostalCode),
                nameof(Location.Name));
        }
    }
}

Beerhall/Views/Brewer/Delete.cshtml
@{
    ViewData["Title"] = "Brewers";
}

<h2>@ViewData["Title"]</h2>

<h4>Please confirm you want to delete brewer @ViewData["Name"]...</h4>

<form asp-action="Delete" method="post">
    <div>
        <button class="btn btn-primary" type="submit">Delete</button>
        <a asp-action="Index" class="btn btn-default">Cancel</a>
    </div>
</form>

Beerhall/Views/Brewer/Edit.cshtml
@model Beerhall.Models.ViewModels.BrewerEditViewModel
@{
    ViewData["Title"] = (bool)ViewData["IsEdit"] ? "Edit brewer" : "Create brewer";
}

<h2>@ViewData["Title"]</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Street"></label>
        <input asp-for="Street" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="PostalCode"></label>
        <select asp-for="PostalCode" asp-items="@ViewData["Locations"] as SelectList" class="form-control">
        <option value="">-- select location --</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Turnover"></label>
        <input asp-for="Turnover" class="form-control"/>
    </div>
    <div>
        <button class="btn btn-primary" type="submit">Save</button>
        <a asp-action="Index" class="btn btn-default">Cancel</a>
    </div>
</form>

Beerhall/Views/Brewer/Index.cshtml
@model IEnumerable<Beerhall.Models.Domain.Brewer>
@{
    ViewData["Title"] = "Brewers";
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-controller="Brewer" asp-action="Create">Voeg een nieuwe brouwer toe</a>
</p>
<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th>Name</th>
        <th>Street</th>
        <th>Location</th>
        <th class="text-right">Turnover</th>
        <th class="text-right">Dete established</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Street</td>
            <td>@item.Location?.PostalCode @item.Location?.Name</td>
            <td class="text-right">@(item.Turnover?.ToString("c") ?? "-")</td>
            <td class="text-right">@(item.DateEstablished?.Date.ToString("d") ?? "-")</td>
            <td>
                <a asp-controller="Brewer" asp-action="Detail" asp-route-id="@item.BrewerId">Detail</a>
                <a asp-controller="Brewer" asp-action="Edit" asp-route-id="@item.BrewerId">Edit</a>
                <a asp-controller="Brewer" asp-action="Delete" asp-route-id="@item.BrewerId">Delete</a>
            </td>
        </tr>
    }
</table>
<p>Total turnover: @($"{(int)ViewData["TotalTurnover"]:C}")</p>